readthedocs/builds/urls.py
"""URL configuration for builds app."""

from django.conf.urls import url
from django.views.generic.base import RedirectView


urlpatterns = [
    url(
        r'^(?P<project_slug>[-\w]+)/(?P<build_pk>\d+)/$',
        RedirectView.as_view(pattern_name='builds_detail', permanent=True),
        name='old_builds_detail',
    ),
    url(
        r'^(?P<project_slug>[-\w]+)/$',
        RedirectView.as_view(pattern_name='builds_project_list', permanent=True),
        name='old_builds_project_list',
    ),
]

readthedocs/gold/urls.py
# -*- coding: utf-8 -*-

"""Gold subscription URLs."""

from django.conf.urls import url

from readthedocs.gold import views
from readthedocs.projects.constants import PROJECT_SLUG_REGEX


urlpatterns = [
    url(r'^$', views.DetailGoldSubscription.as_view(), name='gold_detail'),
    url(
        r'^subscription/$',
        views.UpdateGoldSubscription.as_view(),
        name='gold_subscription',
    ),
    url(
        r'^cancel/$',
        views.DeleteGoldSubscription.as_view(),
        name='gold_cancel',
    ),
    url(r'^projects/$', views.GoldProjectsListCreate.as_view(), name='gold_projects'),
    url(
        (
            r'^projects/remove/(?P<project_slug>{project_slug})/$'.format(
                project_slug=PROJECT_SLUG_REGEX,
            )
        ),
        views.GoldProjectRemove.as_view(),
        name='gold_projects_remove',
    ),
]

readthedocs/proxito/urls.py
"""
A quick rundown of all the URL's we are hoping to parse.

## Projects

pip.rtfd.io/<lang>/<version>/

* Can be single version (pip.rtfd.io/index.html)
* Can be translated (pip.rtfd.io/cz/latest/index.html)
* Can have subprojects (pip.rtfd.io/projects/foo/en/latest/index.html)

## Subprojects

pip.rtfd.io/projects/<slug>/

* Can be single version (pip.rtfd.io/projects/subproject/index.html)
* Can be translated (pip.rtfd.io/projects/subproject/cz/latest/index.html)
* Can't have subprojects (pip.rtfd.io/projects/foo/projects/bar/en/latest/index.html)

## Translations

pip.rtfd.io/<lang>/

* Must be served directly (pip.rtfd.io/cz/latest/index.html)
* Can't be single version (pip.rtfd.io/en/index.html)
    * TODO: Possibly support this, it seems reasonable
* Can't have subprojects (pip.rtfd.io/en/projects/foo/en/latestindex.html)
    * This would stop us from detaching translations from Project modeling
* Can't be translated (pip.rtfd.io/cz/en/latest/index.html)

## Proxied API

pip.rtd.io/_/api/*
"""

from django.conf import settings
from django.conf.urls import include, url
from django.views import defaults

from readthedocs.constants import pattern_opts
from readthedocs.projects.views.public import ProjectDownloadMedia
from readthedocs.proxito.views.serve import (
    ServeDocs,
    ServeError404,
    ServePageRedirect,
    ServeRobotsTXT,
    ServeSitemapXML,
)
from readthedocs.proxito.views.utils import proxito_404_page_handler, fast_404

DOC_PATH_PREFIX = getattr(settings, 'DOC_PATH_PREFIX', '')

urlpatterns = [
    # Serve project downloads
    # /_/downloads/<lang>/<ver>/<type>/
    url(
        (
            r'^{DOC_PATH_PREFIX}downloads/'
            r'(?P<lang_slug>{lang_slug})/'
            r'(?P<version_slug>{version_slug})/'
            r'(?P<type_>[-\w]+)/$'.format(
                DOC_PATH_PREFIX=DOC_PATH_PREFIX,
                **pattern_opts)
        ),
        ProjectDownloadMedia.as_view(same_domain_url=True),
        name='project_download_media',
    ),
    # Serve subproject downloads
    # /_/downloads/<alias>/<lang>/<ver>/<type>/
    url(
        (
            r'^{DOC_PATH_PREFIX}downloads/'
            r'(?P<subproject_slug>{project_slug})/'
            r'(?P<lang_slug>{lang_slug})/'
            r'(?P<version_slug>{version_slug})/'
            r'(?P<type_>[-\w]+)/$'.format(
                DOC_PATH_PREFIX=DOC_PATH_PREFIX,
                **pattern_opts)
        ),
        ProjectDownloadMedia.as_view(same_domain_url=True),
        name='project_download_media',
    ),

    # Serve proxied API
    url(
        r'^{DOC_PATH_PREFIX}api/v2/'.format(
            DOC_PATH_PREFIX=DOC_PATH_PREFIX,
        ),
        include('readthedocs.api.v2.proxied_urls'),
    ),

    # Serve custom 404 pages
    url(
        r'^_proxito_404_(?P<proxito_path>.*)$',
        ServeError404.as_view(),
        name='proxito_404_handler',
    ),
    url(r'robots\.txt$', ServeRobotsTXT.as_view(), name='robots_txt'),
    url(r'sitemap\.xml$', ServeSitemapXML.as_view(), name='sitemap_xml'),

    # # TODO: Support this?
    # (Sub)project `page` redirect
    url(
        r'^(?:projects/(?P<subproject_slug>{project_slug})/)?'
        r'page/(?P<filename>.*)$'.format(**pattern_opts),
        ServePageRedirect.as_view(),
        name='redirect_page_with_filename',
    ),

    # (Sub)project w/ translation and versions
    url(
        (
            r'^(?:projects/(?P<subproject_slug>{project_slug})/)?'
            r'(?P<lang_slug>{lang_slug})/'
            r'(?P<version_slug>{version_slug})/'
            r'(?P<filename>{filename_slug})$'.format(**pattern_opts)
        ),
        ServeDocs.as_view(),
        name='docs_detail',
    ),

    # Hack /en/latest so it redirects properly
    # We don't want to serve the docs here,
    # because it's at a different level of serving so relative links break.
    url(
        (
            r'^(?:projects/(?P<subproject_slug>{project_slug})/)?'
            r'(?P<lang_slug>{lang_slug})/'
            r'(?P<version_slug>{version_slug})$'.format(**pattern_opts)
        ),
        fast_404,
        name='docs_detail_directory_indexing',
    ),

    # # TODO: Support this?
    # # (Sub)project translation and single version
    # url(
    #     (
    #         r'^(?:|projects/(?P<subproject_slug>{project_slug})/)'
    #         r'(?P<lang_slug>{lang_slug})/'
    #         r'(?P<filename>{filename_slug})$'.format(**pattern_opts)
    #     ),
    #     serve_docs,
    #     name='docs_detail',
    # ),

    # (Sub)project single version
    url(
        (
            r'^(?:projects/(?P<subproject_slug>{project_slug})/)?'
            r'(?P<filename>{filename_slug})$'.format(**pattern_opts)
        ),
        ServeDocs.as_view(),
        name='docs_detail_singleversion_subproject',
    ),
]

# Use Django default error handlers to make things simpler
handler404 = proxito_404_page_handler
handler500 = defaults.server_error

readthedocs/urls.py
# pylint: disable=missing-docstring
import os
from functools import reduce
from operator import add

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic.base import RedirectView, TemplateView

from readthedocs.core.urls import core_urls, docs_urls
from readthedocs.core.views import (
    HomepageView,
    do_not_track,
    server_error_404,
    server_error_500,
)
from readthedocs.search import views as search_views
from readthedocs.search.api import PageSearchAPIView


admin.autodiscover()

handler404 = server_error_404
handler500 = server_error_500

basic_urls = [
    url(r'^$', HomepageView.as_view(), name='homepage'),
    url(r'^support/', TemplateView.as_view(template_name='support.html'), name='support'),
    url(r'^security/', TemplateView.as_view(template_name='security.html')),
    url(
        r'^\.well-known/security.txt$',
        TemplateView
        .as_view(template_name='security.txt', content_type='text/plain'),
    ),
]

rtd_urls = [
    url(r'^search/$', search_views.elastic_search, name='search'),
    url(r'^dashboard/', include('readthedocs.projects.urls.private')),
    url(r'^profiles/', include('readthedocs.profiles.urls.public')),
    url(r'^accounts/', include('readthedocs.profiles.urls.private')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^notifications/', include('readthedocs.notifications.urls')),
    url(r'^accounts/gold/', include('readthedocs.gold.urls')),
    # For redirects
    url(r'^builds/', include('readthedocs.builds.urls')),
    # For testing the 404's with DEBUG on.
    url(r'^404/$', handler404),
    # For testing the 500's with DEBUG on.
    url(r'^500/$', handler500),
]

project_urls = [
    url(r'^projects/', include('readthedocs.projects.urls.public')),
]

api_urls = [
    url(r'^api/v2/', include('readthedocs.api.v2.urls')),
    # Keep the `doc_search` at root level, so the test does not fail for other API
    url(r'^api/v2/docsearch/$', PageSearchAPIView.as_view(), name='doc_search'),
    url(
        r'^api-auth/',
        include('rest_framework.urls', namespace='rest_framework')
    ),
    url(r'^api/v3/', include('readthedocs.api.v3.urls')),
]

i18n_urls = [
    url(r'^i18n/', include('django.conf.urls.i18n')),
]

admin_urls = [
    url(r'^admin/', admin.site.urls),
]

dnt_urls = [
    url(r'^\.well-known/dnt/$', do_not_track),

    # https://github.com/EFForg/dnt-guide#12-how-to-assert-dnt-compliance
    url(
        r'^\.well-known/dnt-policy.txt$',
        TemplateView
        .as_view(template_name='dnt-policy.txt', content_type='text/plain'),
    ),
]

debug_urls = []
for build_format in ('epub', 'htmlzip', 'json', 'pdf'):
    debug_urls += static(
        settings.MEDIA_URL + build_format,
        document_root=os.path.join(settings.MEDIA_ROOT, build_format),
    )
debug_urls += [
    url(
        'style-catalog/$',
        TemplateView.as_view(template_name='style_catalog.html'),
    ),

    # This must come last after the build output files
    url(
        r'^media/(?P<remainder>.+)$',
        RedirectView.as_view(url=settings.STATIC_URL + '%(remainder)s'),
        name='media-redirect',
    ),
]

# Export URLs
groups = [
    basic_urls,
    rtd_urls,
    project_urls,
    api_urls,
    core_urls,
    i18n_urls,
]

if settings.DO_NOT_TRACK_ENABLED:
    # Include Do Not Track URLs if DNT is supported
    groups.append(dnt_urls)


if settings.READ_THE_DOCS_EXTENSIONS:
    groups.append([
        url(r'^', include('readthedocsext.urls'))
    ])

if not settings.USE_SUBDOMAIN or settings.DEBUG:
    groups.insert(0, docs_urls)
if settings.ALLOW_ADMIN:
    groups.append(admin_urls)
if settings.DEBUG:
    import debug_toolbar

    debug_urls += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]
    groups.append(debug_urls)

urlpatterns = reduce(add, groups)

readthedocs/search/models.py
"""Search Queries."""

from django.db import models
from django.db.models import Count
from django.db.models.functions import TruncDate
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _

from django_extensions.db.models import TimeStampedModel

from readthedocs.builds.models import Version
from readthedocs.projects.models import Project
from readthedocs.projects.querysets import RelatedProjectQuerySet


class SearchQuery(TimeStampedModel):

    """Information about the search queries."""

    project = models.ForeignKey(
        Project,
        related_name='search_queries',
        on_delete=models.CASCADE,
    )
    version = models.ForeignKey(
        Version,
        verbose_name=_('Version'),
        related_name='search_queries',
        on_delete=models.CASCADE,
    )
    query = models.CharField(
        _('Query'),
        max_length=4092,
    )
    objects = RelatedProjectQuerySet.as_manager()

    class Meta:
        verbose_name = 'Search query'
        verbose_name_plural = 'Search queries'

    def __str__(self):
        return f'[{self.project.slug}:{self.version.slug}]: {self.query}'

    @classmethod
    def generate_queries_count_of_one_month(cls, project_slug):
        """
        Returns the total queries performed each day of the last 30 days (including today).

        Structure of returned data is compatible to make graphs.
        Sample returned data::
            {
                'labels': ['01 Jul', '02 Jul', '03 Jul'],
                'int_data': [150, 200, 143]
            }
        This data shows that there were 150 searches were made on 01 July,
        200 searches on 02 July and 143 searches on 03 July.
        """
        today = timezone.now().date()
        last_30th_day = timezone.now().date() - timezone.timedelta(days=30)

        # this includes the current day also
        last_31_days_iter = [last_30th_day + timezone.timedelta(days=n) for n in range(31)]

        qs = cls.objects.filter(
            project__slug=project_slug,
            created__date__lte=today,
            created__date__gte=last_30th_day,
        ).order_by('-created')

        # dict containing the total number of queries
        # of each day for the past 30 days (if present in database).
        count_dict = dict(
            qs.annotate(created_date=TruncDate('created'))
            .values('created_date')
            .order_by('created_date')
            .annotate(count=Count('id'))
            .values_list('created_date', 'count')
        )

        count_data = [count_dict.get(date) or 0 for date in last_31_days_iter]

        # format the date value to a more readable form
        # Eg. `16 Jul`
        last_31_days_str = [
            timezone.datetime.strftime(date, '%d %b')
            for date in last_31_days_iter
        ]

        final_data = {
            'labels': last_31_days_str,
            'int_data': count_data,
        }

        return final_data

readthedocs/core/forms.py
# -*- coding: utf-8 -*-

"""Forms for core app."""

import logging

from django import forms
from django.contrib.auth.models import User
from django.forms.fields import CharField
from django.utils.translation import ugettext_lazy as _

from .models import UserProfile


log = logging.getLogger(__name__)


class UserProfileForm(forms.ModelForm):
    first_name = CharField(label=_('First name'), required=False, max_length=30)
    last_name = CharField(label=_('Last name'), required=False, max_length=30)

    class Meta:
        model = UserProfile
        # Don't allow users edit someone else's user page
        fields = ['first_name', 'last_name', 'homepage']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        try:
            self.fields['first_name'].initial = self.instance.user.first_name
            self.fields['last_name'].initial = self.instance.user.last_name
        except AttributeError:
            pass

    def save(self, commit=True):
        first_name = self.cleaned_data.pop('first_name', None)
        last_name = self.cleaned_data.pop('last_name', None)
        profile = super().save(commit=commit)
        if commit:
            user = profile.user
            user.first_name = first_name
            user.last_name = last_name
            user.save()
        return profile


class UserDeleteForm(forms.ModelForm):
    username = CharField(
        label=_('Username'),
        help_text=_('Please type your username to confirm.'),
    )

    class Meta:
        model = User
        fields = ['username']

    def clean_username(self):
        data = self.cleaned_data['username']

        if self.instance.username != data:
            raise forms.ValidationError(_('Username does not match!'))

        return data


class UserAdvertisingForm(forms.ModelForm):

    class Meta:
        model = UserProfile
        fields = ['allow_ads']


class FacetField(forms.MultipleChoiceField):

    """
    For filtering searches on a facet.

    Has validation for the format of facet values.
    """

    def valid_value(self, value):
        """
        Although this is a choice field, no choices need to be supplied.

        Instead, we just validate that the value is in the correct format for
        facet filtering (facet_name:value)
        """
        if ':' not in value:
            return False
        return True

readthedocs/api/v2/views/core_views.py
"""Utility endpoints relating to canonical urls, embedded content, etc."""

from django.shortcuts import get_object_or_404
from rest_framework import decorators, permissions, status
from rest_framework.renderers import JSONRenderer
from rest_framework.response import Response

from readthedocs.builds.constants import LATEST
from readthedocs.builds.models import Version
from readthedocs.core.templatetags.core_tags import make_document_url
from readthedocs.projects.models import Project


@decorators.api_view(['GET'])
@decorators.permission_classes((permissions.AllowAny,))
@decorators.renderer_classes((JSONRenderer,))
def docurl(request):
    """
    Get the url that a slug resolves to.

    Example::

        GET https://readthedocs.org/api/v2/docurl/?project=requests&version=latest&doc=index
    """
    project = request.GET.get('project')
    version = request.GET.get('version', LATEST)
    doc = request.GET.get('doc', 'index')
    if project is None:
        return Response(
            {'error': 'Need project and doc'},
            status=status.HTTP_400_BAD_REQUEST,
        )

    project = get_object_or_404(Project, slug=project)
    version = get_object_or_404(
        Version.objects
        .public(request.user, project=project, only_active=False),
        slug=version,
    )
    return Response({
        'url': make_document_url(
            project=project,
            version=version.slug,
            page=doc,
        ),
    })

readthedocs/templates/builds/build_detail.html
{% extends "projects/base_project.html" %}

{% load i18n %}
{% load privacy_tags %}
{% load static %}

{% block title %}{{ build.project.name }}{% endblock %}

{% block extra_scripts %}
  <script type="text/javascript" src="{% static 'vendor/knockout.js' %}"></script>
  <script type="text/javascript" src="{% static 'builds/js/detail.js' %}"></script>
  <script type="text/javascript">
var detail_views = require('builds/detail');
$(document).ready(function () {
    var view = detail_views.BuildDetailView.init({id: '{{ build.pk }}'});
});
  </script>
{% endblock %}

{% block extra_links %}
  <link rel="stylesheet" href="{% static 'builds/css/detail.css' %}" />
{% endblock %}

{% block project_editing %}
  {% with builds_active="active" %}
    {% include "core/project_bar.html" %}
  {% endwith %}
{% endblock %}

{% block content %}
  <div class="build build-detail" id="build-detail">

    <!-- Build meta data -->
    <ul class="build-meta">
      <div data-bind="visible: finished()">
        <li>
          {% trans "Completed" %}
          <span>{{ build.date|date:"N j, Y. P" }}</span>
        </li>

        <li>
          {% trans "Build took" %}
          <span data-bind="text: length">
            {{ build.length }}
          </span>
          {% trans "seconds" %}
        </li>
      </div>

      {% if build.builder and request.user.is_staff %}
        <li>
          {% trans "Built on" %}
          {{ build.builder }}
        </li>
      {% endif %}

      <div data-bind="visible: finished() && success()">
        <li>
          <a data-bind="attr: {href: docs_url}">
            {% trans "View docs" %}
          </a>
        </li>
      </div>

      <div data-bind="visible: finished()">
        <li>
          <a href="{% url "build-detail" build.pk "txt" %}">
            {% trans "View raw" %}
          </a>
        </li>
      </div>
    </ul>

    <div class="build-id">
      {% blocktrans trimmed with build_id=build.pk %}
        Build #{{ build_id }}
      {% endblocktrans %}
    </div>

    <div class="build-version">
      <span class="build-version-slug">
        {% if request.user|is_admin:project and not build.is_external %}
          <a href="{% url "project_version_detail" build.version.project.slug build.version.slug %}">{{ build.version.slug }}</a>
        {% elif build.is_external %}
          {% blocktrans with build.external_version_name as external_version_name %}
            <b>{{ external_version_name }}</b>
          {% endblocktrans %}
            #<a href="{{ build.version.vcs_url }}">{{ build.version.verbose_name }}</a>
        {% else %}
          {{ build.version.slug }}
        {% endif %}
      </span>
      <span class="build-commit" data-bind="visible: commit">
        {% if build.get_commit_url %}
          (<a data-bind="attr: {href: commit_url}"><span data-bind="text: commit">{{ build.commit }}</span></a>)
        {% else %}
            (<span data-bind="text: commit">{{ build.commit }}</span>)
        {% endif %}
      </span>
    </div>

    <div class="build-state">
      <span>
        <span data-bind="visible: !finished(), text: state_display"
              style="display: none;">
          {{ build.get_state_display }}
        </span>
        <img src="{% static 'core/img/loader.gif' %}"
            data-bind="visible: !finished()"
            style="display: none;" />
      </span>
      <span class="build-state-successful"
            data-bind="visible: finished() && success()"
            style="display: none;">
        {% trans "Build completed" %}
      </span>
      <span class="build-state-failed"
            data-bind="visible: finished() && !success()"
            style="display: none;">
        {% trans "Build failed" %}
      </span>
    </div>

    {% if request.user|is_admin:project %}
      {% if not build.success and build.commands.count < 4 and build.version.supports_wipe %}
        <div class="build-ideas">
          <p>
            {% url 'wipe_version' build.version.project.slug build.version.slug as wipe_url %}
            {% blocktrans trimmed %}
              Having trouble with your build environment?
              Try <a href="{{ wipe_url }}">resetting it</a>.
            {% endblocktrans %}
          </p>
        </div>
      {% elif not build.success and "setup.py install" in build.commands.last.output %}
        <div class="build-ideas">
          <p>
            {% url 'projects_advanced' build.version.project.slug as advanced_url %}
            {% blocktrans trimmed %}
              Don't want <em>setup.py install</em> called?
              Change the <strong>Install Project</strong> setting in your <a href="{{ advanced_url }}">advanced settings</a>.
            {% endblocktrans %}
          </p>
        </div>
      {% endif %}
      {% if build.finished and not build.using_latest_config %}
        <div class="build-ideas">
          <p>
            {% blocktrans trimmed with config_file_link="https://docs.readthedocs.io/page/config-file/v2.html" %}
              <strong>Configure your documentation builds!</strong>
              Adding a <a href="{{ config_file_link }}">.readthedocs.yml</a> file to your project
              is the recommended way to configure your documentation builds.
              You can declare dependencies, set up submodules, and many other great features.
            {% endblocktrans %}
          </p>
        </div>
      {% endif %}
    {% endif %}

    {% if build.output %}
      {# If we have build output, this is an old build #}
      <p>
        <button data-bind="visible: !legacy_output(), click: show_legacy_output">
          {% trans "Show full build output" %}
        </button>
      </p>

      <div data-bind="visible: legacy_output"
           style="display: none;">
        <h3>{% trans "Build Output" %}</h3>
        <pre class="build-output"><span id="build-output">{{ build.output }}</span></pre>

        {% if build.setup %}
          <h3>{% trans "Setup Output" %}</h3>
          <pre class="build-output"><span id="build-setup">{{ build.setup }}</span></pre>
        {% endif %}

        {% if build.setup_error %}
          <h3>{% trans "Environment Standard Error" %}</h3>
          <pre class="build-error"><span id="build-setup_error">{{ build.setup_error }}</span></pre>
        {% endif %}
      </div>

      {% if build.error %}
        <h3>{% trans "Build Errors" %}</h3>
        <pre class="build-error"><span id="build-error">{{ build.error }}</span></pre>
      {% endif %}

    {% else %}
      {# Show new command output if lacking build.output #}

      <div class="build-error"
           data-bind="visible: error"
           style="display: none;">
        <h3>{% trans "Error" %}</h3>
        <p class="build-error"
           data-bind="text: error">
          {{ build.error }}
        </p>
        <p>
          {% block github_issue_link %}
            {% if issue_url %}
              {% blocktrans trimmed with url=issue_url %}
                <a href="{{ url }}">Report any build issues here</a>.
              {% endblocktrans %}
            {% endif %}
          {% endblock %}
        </p>
      </div>

      <div id="build-commands"
           class="build-command-list"
           data-bind="visible: commands, foreach: display_commands"
           style="display: none;">
        <div class="build-command"
             data-bind="css: command_status">
          <div class="build-command-run" data-bind="click: toggleCommand">
            <span data-bind="text: command"></span>
          </div>
          <div class="build-command-return"
               data-bind="visible: is_showing">
            <div class="build-command-output">
              <span data-bind="text: output"></span>
            </div>

            <div class="build-command-meta">
              <span class="build-command-time">
                {% trans "Command time:" %}
                <span data-bind="text: run_time">0</span>s
              </span>

              <span class="build-command-exit-code">
                {% trans "Return" %}:
                <span data-bind="text: exit_code"></span>
              </span>
            </div>

          </div>
        </div>
      </div>
    {% endif %}

  </div>
{% endblock %}

readthedocs/templates/builds/build_list.html
{% extends "projects/base_project.html" %}

{% load i18n %}
{% load static %}

{% load pagination_tags %}
{% load privacy_tags %}
{% load projects_tags %}

{% block title %}Builds{% endblock %}

{% block project_editing %}
    {% with builds_active="active" %}
        {% include "core/project_bar.html" %}
    {% endwith %}
{% endblock %}

{% block content %}


<div id="build_list">

        {% autopaginate build_qs 15 %}

        <!-- BEGIN builds list -->
        <div class="module">
          <div class="module-wrapper">

            {% block build_versions %}
            {% if versions and request.user|is_admin:project %}
            <div class="module-header">
              <div style="float:right;">
                <form method="post" action="{% url "builds_project_list" project.slug %}">
                  {% csrf_token %}
                  <ul class="build_a_version">
                    <li style="display: inline-block">
                      <input style="display: inline-block" type="submit" value="{% trans "Build Version:" %}">
                    </li>
                    <li style="display: inline-block">
                      <select id="id_version" name="version_slug">
                      {% for version in versions|sort_version_aware %}
                        <option value="{{ version.slug }}">{{ version.slug }}</option>
                      {% endfor %}
                      </select>
                    </li>
                  </ul>
                </form>
              </div>
            </div>
            {% endif %}
            {% endblock %}

              <h1>{% trans "Recent Builds" %}</h1>
            </div>

            <div class="module-list">
              <div class="module-list-wrapper">
                <ul>
                  {% include "core/build_list_detailed.html" %}
                </ul>
              </div>
            </div>

          </div>
        </div>
        <!-- END builds list -->

        {% paginate %}

</div>

{% endblock %}

{% comment %}

{% block extra_scripts %}
{{ block.super }}
  <script type="text/javascript" src="{% static 'javascript/build_updater.js' %}"></script>

  <script type="text/javascript">
    $(function() {
      {% for build in active_builds %}
        $('#build-{{ build.id }}').effect('highlight', {}, 3000);
        new BuildListUpdater({{ build.id }}).startPolling();
      {% endfor %}
    });
  </script>
{% endblock %}

{% endcomment %}

readthedocs/templates/builds/regexautomationrule_form.html
{% extends "projects/project_edit_base.html" %}

{% load static %}
{% load i18n %}

{% block title %}{% trans "Automation Rule" %}{% endblock %}

{% block nav-dashboard %} class="active"{% endblock %}

{% block project-automation-rules-active %}active{% endblock %}
{% block project_edit_content_header %}{% trans "Automation Rule" %}{% endblock %}


{% block extra_scripts %}
  <script src="{% static "projects/js/automation-rules.js" %}"></script>
  <script type="text/javascript">
    require('projects/automation-rules');
  </script>
{% endblock %}

{% block project_edit_content %}
  <form
      method="post"
      class="form-wide"
      action=".">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="{% trans "Save" %}">
  </form>

  {% if object.pk %}
  <form method="post" action="{% url 'projects_automation_rule_delete' object.project.slug object.pk %}">
    {% csrf_token %}
    <input type="submit" value="{% trans "Delete" %}">
  </form>
  {% endif %}

{% endblock %}

readthedocs/templates/builds/tag_list.html
{% extends "projects/base_project.html" %}

{% load i18n %}

{% block title %}{% trans "Popular tags" %}{% endblock %}

{% block content %}
  <ul>
  {% for tag in tag_list %}
    <li><a href="{% url "projects_tag_detail" tag.slug %}">{{ tag.name }}</a></li>
  {% endfor %}
  </ul>
{% endblock %}